// hplotHandlers.idl : IDL source for hplotHandlers
//

// This file will be processed by the MIDL tool to
// produce the type library (hplotHandlers.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(03af2809-ad88-4c6b-a1cd-470a04fcff02),
	pointer_default(unique)
]
interface IPreview : IUnknown
{
};

[
	object,
	uuid(fb258c7b-0758-41be-aa59-318f5d5fbbbd),
	pointer_default(unique)
]
interface IThumbnail : IUnknown
{
};

[
	object,
	uuid(bd1349aa-9044-4c1d-a88d-aec1b8121e1c),
	pointer_default(unique)
]
interface ISearch : IUnknown
{
};

[
	uuid(cde5882d-6c6a-4db1-9d2a-42b8d1bf55f8),
	version(1.0),
]
library hplotHandlersLib
{
	importlib("stdole2.tlb");
	[
		uuid(5a58cd61-1152-41bf-8b4e-211983b3d596)
	]
	coclass Preview
	{
		[default] interface IPreviewHandler;
	};
	[
		uuid(08c69d66-889d-4481-ba21-86f73d0b8a51)
	]
	coclass Thumbnail
	{
		[default] interface IThumbnailProvider;
	};
	[
		uuid(808b5a26-a5ac-412b-85db-4f9133455b3c)
	]
	coclass Search
	{
		[default] interface IFilter;
	};
};

import "shobjidl.idl";
import "thumbcache.idl";
import "filter.idl";
